// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCcxei8KoYXYZb_yzhtkriFqKwtjkqpRw',
    appId: '1:444631062619:web:52f507f5044a08fbcbc77e',
    messagingSenderId: '444631062619',
    projectId: 'brunel-recycle-77b23',
    authDomain: 'brunel-recycle-77b23.firebaseapp.com',
    storageBucket: 'brunel-recycle-77b23.appspot.com',
    measurementId: 'G-MWBYLNEM5Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCee5EZppRFAohLE-H0vq84E_hMvDaSr9c',
    appId: '1:444631062619:android:cacf456d6d33a8a6cbc77e',
    messagingSenderId: '444631062619',
    projectId: 'brunel-recycle-77b23',
    storageBucket: 'brunel-recycle-77b23.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAk4U9AhHAmF-gpC6M5XXLG51WvoHI9lQ8',
    appId: '1:444631062619:ios:17bb45a1abe8d413cbc77e',
    messagingSenderId: '444631062619',
    projectId: 'brunel-recycle-77b23',
    storageBucket: 'brunel-recycle-77b23.appspot.com',
    iosClientId: '444631062619-teum9p9cr014uo5pqqnfdf00oej17e52.apps.googleusercontent.com',
    iosBundleId: 'com.example.brunelrecycleprototype',
  );
}
